spring:
  application:
    name: expense-tracker
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker}
    username: ${DB_USER:expense_user}
    password: ${DB_PASSWORD:expense_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}